### ISSUE TITLE
Graphql UUID Validation Error

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-be-gw#8]
I found in other systems a bug. If any ID data is posted with the correct format this system works correctly but if that ID's format is incorrect, the system ignores it and converts the wrong data to an empty string.
For example;
UserID : c742f0b0-b538-4dd9-9c5d-bbb8ceb50953 -> User Not Found 
UserID : c742f0b0-b538-4dd9-9c5d-3c4d-bbb8ceb50953 -> Founded User[0] ( this is admin )

I have created a new "graphql.Marshaler" for "uuid" with "gqlgen" in "gqltool" project.

You have to change the models' section in "gqlgen.yml";

```yaml
models:
  ID:
    model:
      - github.com/husamettinarabaci/gqltool/uuid.Uuid
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int32
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int32
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
  Timestamp:
    model:
      - github.com/husamettinarabaci/gqltool/timestamp.Timestamp
  Uuid:
    model:
      - github.com/husamettinarabaci/gqltool/uuid.Uuid 
```
